stages:
  - build
  - test
  - deploy

# Стейдж сборки контейнера
build:
  stage: build
  script:
    - docker build -t my-python-app .

# Стейдж тестирования
test:
  stage: test
  script:
    - docker run --rm my-python-app pytest /test/

# Стейдж деплоя
deploy:
  stage: deploy
  only:
    - master
  before_script:
    - apt-get update -y
    - apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan myserver.com >> ~/.ssh/known_hosts
  script:
    - ssh user@myserver.com 'docker pull my-python-app && docker-compose -f /path/to/docker-compose.yml up -d'
  environment:
    name: production
    url: http://myserver.com
